[project]
name = "taller-ejercicios-python"
version = "0.1.0"
description = "Taller de Python para manejo de datos con nombres cifrados en ROT13"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=3.0.1",
]
